export const categoriesData = [
  "News",
  "Entertainment",
  "Arts",
  "Sports",
  "Movies, Shows & Music",
  "Finance",
  "Productivity",
  "Business Profiles",
  "Shopping",
  "Recommended Content",
  "Travel",
  "Lifestyle",
  "World News",
  "Local News",
  "Political journalism",
  "Science journalism",
];

export const sourcesData = [
  "The Times Of India",
  "BBC NEWS",
  "The New York Times",
  "BBC",
  "CNN",
  "Reuters",
  "Access World News",
  "Fox News",
  "AI Jazeera English",
  "Google News",
  "NBC",
  "NPR",
  "Newspaper",
  "United Press International",
  "Agence Finance-Presse",
  "BuzzFeed",
  "CNBC",
  "The guardian",
  "Yahoo! News",
  "Newslink",
  "USA Today",
  "Wall Street Journal",
  "Bloomberg",
  "Le Monde",
  "The Boston Globe",
  "The Washington Post",
];

export const authorsData = [
  "Thomas Friedman",
  "Fareed Zakaria",
  "David Ignatius",
  "Michela Wrong",
  "Anne Applebaum",
  "Gideon Rachman",
  "Sebastian Payne",
  "Lionel Barber",
  "Zanny Minton Beddoes",
  "John Micklethwait",
  "Ben Rhodes",
  "Masha Gessen",
  "Yasmeen Serhan",
  "Christina Fairbanks",
  "Patrick Kingsley",
  "Liz Sly",
  "James Marson",
  "Demetri Sevastopulo",
  "Edward Luce",
  "Emma Pearson",
  "Michael Georgy",
];
